[package]
name = "pixelmagic-gpu"
description = "OpenGL renderer, shader library and render graph for Pixelmagic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pixelmagic-core.workspace = true
glow.workspace = true
glam.workspace = true
log.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
libloading = "0.8"
